name: Deploy Infra
on: [workflow_dispatch]
jobs:
    Deploy-Noise:
        runs-on: self-hosted
        steps:

            # Noise:
            - name: Yabber about Shrugs
              run: |
               echo "Are shrugs great?"
               echo "Who knows?"
               echo "Lets do a few?!"

    Deploy-Infra:
        needs: Deploy-Noise
        runs-on: self-hosted
        steps:

            - name: Check out repository code
              uses: actions/checkout@v3

            # Troubleshooting:
            - name: List files in the repository
              run: |
                ls -alh ${{ github.workspace }}
            
            # Log into Azure:
            - uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            # Print output:
            - run: echo "This job's status is ${{ job.status }}"