name: Gtihub Actions Demo
on: [push]
jobs:
    Explore-GitHub-Actions:
        runs-on: self-hosted
        steps:
            - name: Yabber about Shrugs
             run: |
               echo "Are shrugs great?"
               echo "Who knows?"
               echo "Lets do a few?!"
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: List files in the repository
              run: |
                ls -alh ${{ github.workspace }}
            - run: echo "This job's status is ${{ job.status }}"