name: Deploy Infra
on: [push]
jobs:
    Deploy-Infra:
        runs-on: self-hosted
        steps:

            # Noise:
            - name: Yabber about Shrugs
              run: |
               echo "Are shrugs great?"
               echo "Who knows?"
               echo "Lets do a few?!"

            - name: Check out repository code
              uses: actions/checkout@v3

            # Troubleshooting:
            - name: List files in the repository
              run: |
                ls -alh ${{ github.workspace }}
            
            # Log into Azure:
            - uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            # Deploy:
            - name: Deploy Blue
              uses: azure/arm-deploy@v1
              with:
                subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
                resourceGroupName: sjr-blue-rg
                template: ./main.bicep
                parameters: ./main.parameters.json

            # Print output:
            - run: echo "This job's status is ${{ job.status }}"